apiVersion: apps/v1
kind: Deployment 
metadata:
  name: jenkins-demo

spec:
  replicas: 3
  selector:
    matchLabels:
      app: jenkins-demo
  template:
    metadata:
      labels:
        app: jenkins-demo
    spec:
      containers:
      - name: app
        image: johnvelan/jenkins-docker-demo:latest
        imagePullPolicy: Always

        ports:
        - containerPort: 3000